// <auto-generated />
using System;
using Hometask.OrderManager.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hometask.OrderManager.Data.EF.Migrations
{
    [DbContext(typeof(CHIITDbContext))]
    [Migration("20250712134233_ControlMigration")]
    partial class ControlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Analysis", b =>
                {
                    b.Property<Guid>("AnId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("an_id");

                    b.Property<decimal?>("AnCost")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("an_cost");

                    b.Property<Guid?>("AnGroup")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("an_group");

                    b.Property<string>("AnName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("an_name");

                    b.Property<decimal?>("AnPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("an_price");

                    b.HasKey("AnId")
                        .HasName("PK__Analysis__831DABF3BC7A571F");

                    b.HasIndex("AnGroup");

                    b.ToTable("Analysis", (string)null);
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Group", b =>
                {
                    b.Property<Guid>("GrId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("gr_id");

                    b.Property<string>("GrName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gr_name");

                    b.Property<decimal?>("GrTemp")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("gr_temp");

                    b.HasKey("GrId")
                        .HasName("PK__Groups__2BC0F88E02FCCB78");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Order", b =>
                {
                    b.Property<Guid>("OrdId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ord_id");

                    b.Property<Guid?>("OrdAn")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ord_an");

                    b.Property<DateTime?>("OrdDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("ord_datetime");

                    b.HasKey("OrdId")
                        .HasName("PK__Orders__DC39D7DF5F23AF78");

                    b.HasIndex("OrdAn");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Analysis", b =>
                {
                    b.HasOne("Hometask.OrderManager.Data.EF.Models.Group", "AnGroupNavigation")
                        .WithMany("Analyses")
                        .HasForeignKey("AnGroup")
                        .HasConstraintName("FK_Analysis_Groups");

                    b.Navigation("AnGroupNavigation");
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Order", b =>
                {
                    b.HasOne("Hometask.OrderManager.Data.EF.Models.Analysis", "OrdAnNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("OrdAn")
                        .HasConstraintName("FK_Orders_Analysis");

                    b.Navigation("OrdAnNavigation");
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Analysis", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Hometask.OrderManager.Data.EF.Models.Group", b =>
                {
                    b.Navigation("Analyses");
                });
#pragma warning restore 612, 618
        }
    }
}
