using Hometask.OrderManager.Data.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hometask.OrderManager.Data.EF.Configurations;

public class AnalysisConfiguration : IEntityTypeConfiguration<Analysis>
{
    public void Configure(EntityTypeBuilder<Analysis> builder)
    {
        // auto-generated by scaffolding, decided to keep
        builder.HasKey(e => e.AnId).HasName("PK__Analysis__831DABF3BC7A571F");

        builder.ToTable("Analysis");

        builder.Property(e => e.AnId)
            .ValueGeneratedNever()
            .HasColumnName("an_id");
        builder.Property(e => e.AnCost)
            .HasColumnType("decimal(10, 2)")
            .HasColumnName("an_cost");
        builder.Property(e => e.AnGroup).HasColumnName("an_group");
        builder.Property(e => e.AnName)
            .HasMaxLength(100)
            .HasColumnName("an_name");
        builder.Property(e => e.AnPrice)
            .HasColumnType("decimal(10, 2)")
            .HasColumnName("an_price");

        builder.HasOne(d => d.AnGroupNavigation).WithMany(p => p.Analyses)
            .HasForeignKey(d => d.AnGroup)
            .HasConstraintName("FK_Analysis_Groups");
    }
}
