using Hometask.OrderManager.Data.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hometask.OrderManager.Data.EF.Configurations;

public class GroupConfiguration : IEntityTypeConfiguration<Group>
{
    public void Configure(EntityTypeBuilder<Group> builder)
    {
        // auto-generated by scaffolding, decided to keep
        builder.HasKey(e => e.GrId).HasName("PK__Groups__2BC0F88E02FCCB78");

        builder.Property(e => e.GrId)
            .ValueGeneratedNever()
            .HasColumnName("gr_id");
        builder.Property(e => e.GrName)
            .HasMaxLength(50)
            .HasColumnName("gr_name");
        builder.Property(e => e.GrTemp)
            .HasColumnType("decimal(5, 2)")
            .HasColumnName("gr_temp");
    }
}
