using Hometask.OrderManager.Data.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hometask.OrderManager.Data.EF.Configurations;

public class OrderConfiguration : IEntityTypeConfiguration<Order>
{
    public void Configure(EntityTypeBuilder<Order> builder)
    {
        // auto-generated by scaffolding, decided to keep
        builder.HasKey(e => e.OrdId).HasName("PK__Orders__DC39D7DF5F23AF78");

        builder.Property(e => e.OrdId)
            .ValueGeneratedNever()
            .HasColumnName("ord_id");
        builder.Property(e => e.OrdAn).HasColumnName("ord_an");
        builder.Property(e => e.OrdDatetime)
            .HasColumnType("datetime")
            .HasColumnName("ord_datetime");

        builder.HasOne(d => d.OrdAnNavigation).WithMany(p => p.Orders)
            .HasForeignKey(d => d.OrdAn)
            .HasConstraintName("FK_Orders_Analysis");
    }
}
